name: Docs creation

env:
  PR_NUMBER: ${{ github.event.number }}

on: 
  push:
    branches:
  pull_request: 
    branches: [gh-pages]
    types: [opened, synchronize, closed]

jobs:
  docs:
  # deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst-parser sphinx-notfound-page
          pip install sphinxawesome-theme --pre

      - name: Sphinx build
        run: |
          sphinx-build docs/ build/

      - name: Deploy Docs on Push (Staging)
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}
        with:
          publish_branch: build-push
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          destination_dir: staging/${PR_NUMBER}/
          force_orphan: true

      - name: Deploy Docs on Merge (Production)
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'pull_request' && github.ref == 'refs/heads/gh-pages' }}

        with:
          publish_branch: build-main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          destination_dir: /
          force_orphan: true